### ISSUE TITLE
Fix nuget pack warnings on Windows

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/ZPT-Sharp#66]
Warnings are in this kind of format - all because I didn't put the files into a `net45` directory:

```
AfterBuild:
  "C:\Program Files (x86)\NuGet\nuget.exe" pack CSF.Zpt.nuspec -Prop Configuration=Release
  Attempting to build package from 'CSF.Zpt.nuspec'.
  Successfully created package 'C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\CSF.Zpt\CSF.Zpt.0.3.0.nupkg'.

EXEC : warning : 3 issue(s) found with package 'CSF.Zpt'. [C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\CSF.Zpt\CSF.Zpt.csproj]

  Issue: Assembly not inside a framework folder.
  Description: The assembly 'lib\CSF.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder.
  Solution: Move it into a framework-specific folder. If this assembly is targeted for multiple frameworks, ignore this warning.

  Issue: Assembly not inside a framework folder.
  Description: The assembly 'lib\CSF.Zpt.Api.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder.
  Solution: Move it into a framework-specific folder. If this assembly is targeted for multiple frameworks, ignore this warning.

  Issue: Assembly not inside a framework folder.
  Description: The assembly 'lib\CSF.Zpt.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder.
  Solution: Move it into a framework-specific folder. If this assembly is targeted for multiple frameworks, ignore this warning.
Done Building Project "C:\Users\Craig.Fowler\Documents\Visual Studio 2015\Projects\ZPT-Sharp\CSF.Zpt\CSF.Zpt.csproj" (default targets).
```
